server:
  port: 9006

spring:
  datasource:
      url: jdbc:mysql:///hrm-page?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf8

hrm:
  swagger:
    titel:页面静态化管理服务
    description: 页面静态化管理服务接口文档

feign:
  hystrix:
    enabled: true

