server:
  port: 9008

spring:
  datasource:
      url: jdbc:mysql:///hrm-user?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf8

hrm:
  swagger:
    titel: 用户管理服务
    description: 用户管理服务接口文档

feign:
  hystrix:
    enabled: true

